import = [
    #"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    #"~/.config/alacritty/themes/themes/dracula.toml"
    #"~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
    #"~/.config/alacritty/themes/themes/kanagawa_wave.toml"
    #"~/.config/alacritty/themes/themes/seashells.toml"
    #"~/.config/alacritty/themes/themes/horizon-dark.toml"
    #"~/.config/alacritty/themes/themes/cyberdream.toml"
    #"~/.config/alacritty/themes/themes/tokyo-night.toml"
    "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
]
[env]
TERM = "xterm-256color"

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
bold = {family = "FiraCode Nerd Font Mono",style = "Bold"}
italic = {family = "FiraCode Nerd Font Mono",style = "Italic"}
size = 12.0

[window]
decorations = "None"
opacity = 0.5
blur = true

[mouse]
hide_when_typing = true

[cursor]
style = {shape = "Block", blinking = "always"}
