import = [
    #"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    #"~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
    #"~/.config/alacritty/themes/themes/seashells.toml"
]
[env]
TERM = "xterm-256color"

[font]
normal = {family = "MesloLGS NF", style = "Regular"}
bold = {family = "MesloLGS NF",style = "Bold"}
italic = {family = "MesloLGS NF",style = "Italic"}
size = 10.0

[window]
decorations = "None"
opacity = 0.6
blur = true

[mouse]
hide_when_typing = true

[cursor]
style = {shape = "Block", blinking = "always"}
