palette = "catppuccin_mocha"

format = """
$directory\
[](fg:base bg:mauve)\
[](fg:lavender bg:base)\
$git_branch\
$git_state\
$git_metrics\
[](fg:base bg:lavender)\
$git_status\
[](fg:green bg:base)\
$nodejs\
$python\
[](bg:green fg:base)\
$fill\
[](fg:lavender)\
$cmd_duration\ 
[](bg:lavender fg:base)\
[](bg:base fg:mauve)\
$time\
$line_break\
$character"""

[fill]
symbol=" "

[directory]
style="bg:mauve fg:surface0 bold"
read_only=" "
format="[ $path ]($style)"
truncation_length=2

[character]
success_symbol="[➤](surface2)"
error_symbol="[✗](red)"

[git_status]
style="bg:base"
untracked="[?${count}](bg:base fg:#44eeff bold)"
ahead="[⇡](bg:base fg:#55dd00 bold)"
behind="[⇣](bg:base fg:#55dd00 bold)"
modified="[!${count}](bg:base fg:#55aaff bold)"
deleted="[✘${count}](bg:base fg:#ff7700 bold)"
staged="[+${count}](bg:base fg:#55dd00 bold)"
stashed="[#${count}](bg:base fg:#ffdd00 bold)"
format="[( ($untracked )($ahead )($behind )($modified )($deleted )($staged )($stashed ))]($style)"

[git_branch]
style="bg:lavender fg:surface0 bold"
symbol=""
truncation_length=9
truncation_symbol="…"
only_attached=true
format="[ $symbol $branch ]($style)"

[nodejs]
style="bg:green fg:surface0 bold"
symbol = " "
format="[ $symbol($version )]($style)"

[python]
style="bg:green fg:surface0 bold"
symbol = " "
format="[ ${symbol}${pyenv_prefix}(${version} )($virtualenv )]($style)"

[cmd_duration]
style="bg:lavender fg:surface0 bold"
format="[ $duration ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:mauve fg:surface0 bold"
format = '[ $time ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
