format = """
$directory\
[](fg:#4f000b bg:#720026)\
$git_branch\
$git_state\
$git_metrics\
[](fg:#720026 bg:#ce4257)\
$git_status\
[](fg:#ce4257 bg:#ff7f51)\
$nodejs\
$python\
[](fg:#ff7f51)\
$fill\
[\uf0d9](fg:#ff9b54)\
$time\
$cmd_duration\ 
$line_break\
$character"""

[fill]
symbol=" "

[directory]
style="bg:#4f000b"
read_only=" "
format="[ $path ]($style)"
truncation_length=2

[character]
success_symbol="[➤](bright-black)"
error_symbol="[✗](red)"

[git_status]
style="bg:#ce4257"
untracked="[?${count}](bg:#ce4257 fg:#44eeff)"
ahead="[⇡](bg:#ce4257 fg:#55dd00)"
behind="[⇣](bg:#ce4257 fg:#55dd00)"
modified="[!${count}](bg:#ce4257 fg:#55aaff)"
deleted="[✘${count}](bg:#ce4257 fg:#ff7700)"
staged="[+${count}](bg:#ce4257 fg:#55dd00)"
stashed="[#${count}](bg:#ce4257 fg:#ffdd00)"
format="[( ($untracked )($ahead )($behind )($modified )($deleted )($staged )($stashed ))]($style)"

[git_branch]
symbol=""
style="bg:#720026"
truncation_length=9
truncation_symbol="…"
only_attached=true
format="[ $symbol $branch ]($style)"

[nodejs]
style="bg:#ff7f51"
symbol = " "
format="[ $symbol($version )]($style)"

[python]
style="bg:#ff7f51"
symbol = " "
format="[ ${symbol}${pyenv_prefix}(${version} )($virtualenv )]($style)"

[cmd_duration]
style="bg:#ff9b54"
format="[ $duration ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#ff9b54"
format = '[ $time ]($style)'
